### PR TITLE
Multiple file inputs bug

### PR DESCRIPTION
**Pull request by asgerb**
Tested out the JS implementation and it works swell

### CODE REVIEW

**Comment by tomasc** [comment]
Thanks, @asgerb!
Merged and released as `1.2.0`.

**Comment by tomasc** [comment]
Hi @asgerb , looks like we have some bug in the JS – at least in my app all inputs ids (not only the file) have the unique hash appended. Do you experience the same?

**Comment by asgerb** [comment]
Didn't notice this and as far as I see it's not happening here. Can you explain the steps you are doing? Then I'll try to reproduce.

**Comment by tomasc** [comment]
Ah ok, sorry, it's some other plugin messing with me ;-)

**Pull request merged**
